accent_map = {
    "Afro-Asiatic": 0,
    "Austro-Asiatic": 1,
    "Austronesian": 2,
    "Indo-European": 3, 
    "Japonic": 4,
    "Koreanic":5,
    "Sino-Tibetan":6,
    "Turkic": 7,
    "NorthAmerica": 8,
    "Europe": 9,
    "Australian": 10,
    "Africa": 11,
    "Caribbean": 12,
    "Asia": 13,
    
    }


language_family = {
            "NorthAmerica": ['us', 'canada', 'mainstream us english'],
            "Europe": ['uk', 'england', 'wales', 'scotland', 'ireland', 'southern british english', 'english', 'scottish english', 'irish english'],
            "Australian": ['australia', 'newzealand'],
            "Africa": ['african', 'south african english', 'southatlandtic', 'nigerian english', "kenyan english", "ghanain english"],
            "Caribbean": ['jamaican', 'trinidadian', 'barbadian', 'bermuda', 'jamaican english' ],
            "Asia": ['singapore', 'hongkong', 'philippines', 'malaysia', 'indian', 'indian english', 'sinhalese'],

            "Austronesian": ['indonesian', 'malay', 'carolinian', 'cebuano', 'chamorro','fijian', 'filipino', 'gaddang', 'hiligaynon', 'javanese',
                        'lamaholot', 'malagasy', 'masbatenyo', 'mortlockese', 'pohnpeian', 'rotuman', 'satawalese', 'tagalog', 'yapese',
                        'lamotrekese', 'sundanese', 'bahasa' ],
            "Afro-Asiatic": ['amharic', 'arabic', 'chaldean', 'gedeo', 'hadiyya', 'hausa', 'hebrew', 'kabyle', 'kambaata', 'maltese', 'oromo',
                'sarua', 'somali', 'tigre', 'tigrigna', 'amazigh', 'maltese'],
            "Austro-Asiatic": ['khmer', 'vietnamese'],
            "Dravidian": ['kannada', 'malayalam', 'tamil', 'telugu'],
            "Eskimo-Aleut": ['yupik'],
            "Hmong-Mien": ['hmong'],
            "Isolate": ['basque'],
            "Indo-European": ['afrikaans', 'albanian', 'armenian', 'bengali', 'bavarian', 'bosnian','bulgarian', 'catalan', 'chittagonian', 
                                'croatian', 'czech', 'danish', 'dari', 'dutch','english', 'spanish', 'swedish', 'faroese', 'french', 'frisian',
                                'german', 'greek', 'gujarati', 'hindi', 'hindko', 'icelandic', 'italian', 'konkani', 'kurdish',
                                'latvian', 'lithuanian', 'macedonian', 'marathi', 'nepali', 'norwegian', 'serbian', 'slovak', 'oriya', 'ossetic',
                                'punjabi', 'pashto', 'polish', 'portuguese', 'russian', 'romanian', 'sardinian', 'sindhi', 'sinhala', 'sicilian',
                                'swiss', 'sylheti', 'ukrainian', 'urdu', 'yiddish', 'belarusan', 'charapa-spanish', 'farsi', 'vlaams', 'luxembourgeois',
                                'slovenian', 'tajiki', 'montenegrin', "portoguese", "spanish (mexican)"],
                                
            "Japonic": ['japanese'],
            "Kartvelian": ['georgian' ],
            "Koreanic": ['korean'],
            "Kra-Dai": ['lao', 'shan', 'thai'],
            "Maipurean":  ['garifuna'],
            "Mongolic": ['mongolian'],
            "Misumalpan": ['miskito'],
            "Niger-Congo": ['akan', 'baga', 'agni', 'bafang', 'zulu', 'bamun', 'chichewa', 'jola', 'ebira', 'edo', 'ewe', 'fang', 'fulfulde', 'ga',
                            'ganda', 'ibibio', 'ife', 'igbo', 'kalanga', 'kamba', 'kikongo', 'lingala', 'luba-kasai', 'rwanda', 'rundi', 'mankanya',
                            'mandinka', 'mende', 'moba', 'moore', 'ndebele', 'ngemba', 'pulaar', 'shona', 'susu', 'tumbuka', 'voro', 'wolof', 'yoruba',
                            'ashanti', 'fanti', 'twi', 'balanta', 'bambara', 'bayangi', 'gusii', 'kikuyu', 'kiswahili', 'kru', 'tswana', 'temne'],
            "Nilo-Saharan": ['bari','dinka', 'kanuri', 'nandi', 'nuer', 'shilluk', 'wali', 'luo', 'mandingo', 'serer', 'sesotho', 'xasonga'],
            "Sino-Tibetan": ['bai', 'burmese', 'cantonese', 'mizo', 'hakka', 'mandarin', 'min', 'hainanese' ,'naxi', 'taiwanese','wu', 'xiang', 'pahari',
                            'tibetan', 'gan', 'teochew', 'newari', 'taishan', 'chinese'],
            "South-Central Papuan": ['nama'],
            "Turkic": ['azerbaijani', 'kazakh', 'kyrgyz', 'tatar', 'turkish', 'turkmen', 'uyghur', 'uzbek', 'yakut'],
            "Trans-New Guinea": ['fataluku'],
            "Uralic": ['finnish', 'estonian', 'hungarian'],
            "Sign": ['home'],
            "Pidgin": ['liberian'],
            "Creole": ['krio', 'haitian', 'mauritian', 'papiamentu'],
            "Quechuan": ['quechua'],
            "Other": ['synthesized', 'northern', 'tok' ],
}
language_family_dict = {lang: family for family, langs in language_family.items() for lang in langs}